version: '3.8'

services:
  db:
    container_name: 'pg_db_container'
    image: 'postgres'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: quiz_app_db
    ports:
      - '5432:5432'
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: 'pgadmin_container'
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pg.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgdata
volumes:
  local_pgdata:
  pgadmin-data: